server:
  servlet:
    context-path: /restAndSwagger
  port: 8090
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/liquibase/master.xml
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver